"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Products = exports.States = void 0;
var States;
(function (States) {
    States["AndhraPradesh"] = "AP";
    States["ArunachalPradesh"] = "AR";
    States["Assam"] = "AS";
    States["Bihar"] = "BR";
    States["Chhattisgarh"] = "CG";
    States["Goa"] = "GA";
    States["Gujarat"] = "GJ";
    States["Haryana"] = "HR";
    States["HimachalPradesh"] = "HP";
    States["Jharkhand"] = "JH";
    States["Karnataka"] = "KA";
    States["Kerala"] = "KL";
    States["MadhyaPradesh"] = "MP";
    States["Maharashtra"] = "MH";
    States["Manipur"] = "MN";
    States["Meghalaya"] = "ML";
    States["Mizoram"] = "MZ";
    States["Nagaland"] = "NL";
    States["Odisha"] = "OD";
    States["Punjab"] = "PB";
    States["Rajasthan"] = "RJ";
    States["Sikkim"] = "SK";
    States["TamilNadu"] = "TN";
    States["Telangana"] = "TS";
    States["Tripura"] = "TR";
    States["UttarPradesh"] = "UP";
    States["Uttarakhand"] = "UK";
    States["WestBengal"] = "WB";
    States["AndamanAndNicobarIslands"] = "AN";
    States["Chandigarh"] = "CH";
    States["DadraAndNagarHaveliAndDamanAndDiu"] = "DN";
    States["Lakshadweep"] = "LD";
    States["Delhi"] = "DL";
    States["Puducherry"] = "PY";
})(States || (exports.States = States = {}));
var Products;
(function (Products) {
    Products[Products["Keyboard"] = 1599] = "Keyboard";
    Products[Products["Mouse"] = 799] = "Mouse";
    Products[Products["Monitor"] = 6999] = "Monitor";
    Products[Products["Laptop"] = 54999] = "Laptop";
    Products[Products["Headphones"] = 2999] = "Headphones";
    Products[Products["Webcam"] = 1299] = "Webcam";
    Products[Products["Printer"] = 3499] = "Printer";
    Products[Products["USBDrive"] = 699] = "USBDrive";
    Products[Products["Charger"] = 499] = "Charger";
    Products[Products["Backpack"] = 1499] = "Backpack";
    Products[Products["DeskLamp"] = 899] = "DeskLamp";
    Products[Products["MousePad"] = 399] = "MousePad";
})(Products || (exports.Products = Products = {}));
