export enum States {
    AndhraPradesh = 'AP',
    ArunachalPradesh = 'AR',
    Assam = 'AS',
    Bihar = 'BR',
    Chhattisgarh = 'CG',
    Goa = 'GA',
    Gujarat = 'GJ',
    Haryana = 'HR',
    HimachalPradesh = 'HP',
    Jharkhand = 'JH',
    Karnataka = 'KA',
    Kerala = 'KL',
    MadhyaPradesh = 'MP',
    Maharashtra = 'MH',
    Manipur = 'MN',
    Meghalaya = 'ML',
    Mizoram = 'MZ',
    Nagaland = 'NL',
    Odisha = 'OD',
    Punjab = 'PB',
    Rajasthan = 'RJ',
    Sikkim = 'SK',
    TamilNadu = 'TN',
    Telangana = 'TS',
    Tripura = 'TR',
    UttarPradesh = 'UP',
    Uttarakhand = 'UK',
    WestBengal = 'WB',
    AndamanAndNicobarIslands = 'AN',
    Chandigarh = 'CH',
    DadraAndNagarHaveliAndDamanAndDiu = 'DN',
    Lakshadweep = 'LD',
    Delhi = 'DL',
    Puducherry = 'PY'
}

export enum Products {
    Keyboard = 1599,
    Mouse = 799,
    Monitor = 6999,
    Laptop = 54999,
    Headphones = 2999,
    Webcam = 1299,
    Printer = 3499,
    USBDrive = 699,
    Charger = 499,
    Backpack = 1499,
    DeskLamp = 899,
    MousePad = 399
}